# タイトル
title: KAKITOME

# サブタイトル
description: akihiros.github.io

# テーマ
theme: just-the-docs
url: https://akihiros.github.io

# ロゴ/ファビコン
# logo: "/assets/myicon.png"
favicon_ico: "./assets/myicon.png"

# 補助リンク
# aux_links:
#   "Just the Docs on GitHub":
#     - "//github.com/just-the-docs/just-the-docs"

# 見出しアンカーリンク
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2024-2025 akihiros All rights reserved."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# テーマカラー
# color_scheme: dark

# plugins:
#   - jekyll-feed
#   - jekyll-sitemap
#   - jekyll-last-modified-at
